apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-claim
  labels:
    task: monitoring
    k8s-app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storageclass
  resources:
    requests:
      storage: 10Gi

